linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.25
  gocyclo:
    min-complexity: 14
  maligned:
    suggest-new: true
  dupl:
    threshold: 150
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/Cypherpunkarmory/punch
  gocritic:
    enabled-tags:
      - style
      - experimental
      - diagnostic
    disabled-checks:
      - commentFormatting
      - paramTypeCombine

linters:
  enable-all: true
  disable:
    - prealloc
    - gochecknoglobals
    - gochecknoinits
    - unconvert

issues:
  exclude-rules:
    - path: "restapi/"
      linters:
        - dupl
    - path: "cmd/"
      linters:
        - dupl
    - path: "cmd/"
      text: "(viper.|MarkFlag|telnet)"
      linters:
        - errcheck

run:
  skip-dirs:
    - cmd/test
    - cmd/test-files
    - tunnel/test-files
  skip-files:
    - cmd/test/test-helpers.go
  deadline: 1m
  tests: false