language: go

env:
  - GO111MODULE=on

# You don't need to test on very old version of the Go compiler. It's the user's
# responsibility to keep their compilers up to date.
go:
  - 1.11.x

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

# Only clone the most recent commit.
git:
  depth: 1

branches:
  only:
  - /\d+\.\d+\.\d+/
  - master

install: true
# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - go test ./... -tags unit -coverprofile=coverage.out
  - godacov -t ${CODACY_TOKEN} -r ./coverage.out -c ${TRAVIS_COMMIT}
  - make ROLLBAR_TOKEN=${ROLLBAR_TOKEN} VERSION=${TRAVIS_TAG} all   

deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file: 
      - "punch-darwin-amd64"
      - "punch-darwin-386"
      - "punch-linux-amd64"
      - "punch-linux-386"
      - "punch-windows-amd64.exe"
      - "punch-windows-386.exe"
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    local_dir: gh-pages/
    github-token: ${GH_TOKEN}
    on:
      tags: true
