language: go

env:
  - GO111MODULE=on

# You don't need to test on very old version of the Go compiler. It's the user's
# responsibility to keep their compilers up to date.
go:
  - 1.11.x

# Only clone the most recent commit.
git:
  depth: 1

branches:
  only:
  - /v\d+\.\d+\.\d+/
  - master

install: true
# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - make ROLLBAR_TOKEN=${ROLLBAR_TOKEN} VERSION=${VERSION} all     

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: 
    - "punch-darwin-amd64"
    - "punch-darwin-386"
    - "punch-linux-amd64"
    - "punch-linux-386"
    - "punch-windows-amd64.exe"
    - "punch-windows-386.exe"
  skip_cleanup: true
  on:
    tags: true