package cmd

import (
	"errors"
	"os"
	"strconv"
	"strings"
	"sync"

	"github.com/cypherpunkarmory/punch/tunnel"
	"github.com/reiver/go-telnet"
	"github.com/spf13/cobra"
)

type tunnelConf struct {
	port        int
	forwardType string
}

var itCmd = &cobra.Command{
	Use:   "it [ports]",
	Short: "Expose a web server on the ports you specify",
	Long: `To expose a http web server on port 5000 and https web server on port 5001
			 punch it http:5000 https:5001`,
	Args: cobra.MinimumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		var err error
		var confs = make([]tunnelConf, len(args))
		for index, conf := range args {
			confs[index], err = getTunnelConfig(conf)
			if err != nil {
				break
			}
		}
		if err != nil {
			if args[0] == "chewie" {
				var caller telnet.Caller = telnet.StandardCaller
				telnet.DialToAndCall("towel.blinkenlights.nl:23", caller)
				os.Exit(1)
			}
			reportError("Input does not match the correct syntax type:port", true)
		}
		tunnelMultiple(confs)
	},
}

func getTunnelConfig(input string) (tunnelConf, error) {
	var output tunnelConf
	var err error
	conf := strings.Split(input, ":")
	if len(conf) != 2 {
		return output, errors.New("bad input")
	}
	output.forwardType = conf[0]
	output.port, err = strconv.Atoi(conf[1])
	if err != nil {
		return output, errors.New("bad input")
	}
	return output, nil
}

func init() {
	rootCmd.AddCommand(itCmd)
	itCmd.Flags().StringVarP(&subdomain, "subdomain", "s", "", "If not selected domain name will be autogenerated")
}

func tunnelMultiple(confs []tunnelConf) {
	var tunnelConfigs = make([]tunnel.Config, len(confs))
	protocol := make([]string, len(confs))
	if subdomain != "" && !checkSubdomain(subdomain) {
		reportError("Invalid Subdomain", true)
	}
	publicKey, err := getPublicKey(publicKeyPath)
	if err != nil {
		os.Exit(3)
	}
	for index, t := range confs {
		protocol[index] = t.forwardType
	}
	response, err := restAPI.CreateTunnelAPI(subdomain, publicKey, protocol)
	if err != nil {
		reportError(err.Error(), true)
	}
	if subdomain == "" {
		subdomain, _ = restAPI.GetSubdomainName(response.Subdomain.ID)
	}

	for index, conf := range confs {
		if !checkPort(conf.port) {
			reportError("Port is not in range[1-65535]", true)
			err := restAPI.DeleteTunnelAPI(subdomain)
			if err != nil {
				reportError("Could not delete tunnel. Use punch cleanup "+subdomain, true)
			}
		}
		tunnelConfigs[index] = tunnel.Config{
			ConnectionEndpoint: sshEndpoint,
			RestAPI:            restAPI,
			TunnelEndpoint:     response,
			EndpointType:       conf.forwardType,
			PrivateKeyPath:     privateKeyPath,
			EndpointURL:        baseURL,
			LocalPort:          conf.port,
			Subdomain:          subdomain,
		}
	}
	var wg sync.WaitGroup
	wg.Add(len(tunnelConfigs))
	for i := 0; i < len(tunnelConfigs); i++ {
		go tunnel.StartReverseTunnel(&tunnelConfigs[i], &wg)
	}
	wg.Wait()

}
