package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

// releaseCmd represents the release command
var releaseCmd = &cobra.Command{
	Use:   "release -s [subdomain]",
	Short: "Release subdomain",
	Long:  `Release a subdomain you have reserved`,
	Run: func(cmd *cobra.Command, args []string) {
		release(subdomain)
	},
}

func init() {
	subdomainCmd.AddCommand(releaseCmd)
	releaseCmd.Flags().StringVarP(&subdomain, "subdomain", "s", "", "If not selected domain name will be autogenerated")
	releaseCmd.MarkFlagRequired("subdomain")
}

func release(subdomain string) {
	if !checkSubdomain(subdomain) {
		reportError("Invalid Subdomain", true)
	}
	err := restAPI.ReleaseSubdomainAPI(subdomain)
	if err != nil {
		reportError(err.Error(), true)
	}
	fmt.Println("Successfully released subdomain")
}
