package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

// reserveCmd represents the reserve command
var reserveCmd = &cobra.Command{
	Use:   "reserve -s [subdomain]",
	Short: "Reserve a subdomain",
	Long:  `Reserve a subdomain to secure the subdomain for future use. Once reserved only you can use it`,
	Run: func(cmd *cobra.Command, args []string) {
		reserve()
	},
}

func init() {
	subdomainCmd.AddCommand(reserveCmd)
	reserveCmd.Flags().StringVarP(&subdomain, "subdomain", "s", "", "If not selected domain name will be autogenerated")
	reserveCmd.MarkFlagRequired("subdomain")
}

func reserve() {
	if !checkSubdomain(subdomain) {
		reportError("Invalid Subdomain", true)
	}

	response, err := restAPI.ReserveSubdomainAPI(subdomain)
	if err != nil {
		reportError(err.Error(), true)
	}
	fmt.Println("Successfully reserved subdomain " + response.Name)
}
