// Copyright © 2018 NAME HERE <EMAIL ADDRESS>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"fmt"
	"os"

	"strconv"

	"github.com/cypherpunkarmory/punch/tunnel"
	"github.com/cypherpunkarmory/punch/utilities"
	"github.com/spf13/cobra"
)

// httpsCmd represents the https command
var GenerateCert bool
var tlsCmd = &cobra.Command{
	Use:   "tls",
	Short: "Expose a https web server over the port you specify",
	Long:  `To expose a https web server on port 443 punch https -p 443`,
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		var err error
		Port, err = strconv.Atoi(args[0])
		if err != nil {
			fmt.Println("Must supply a port to forward")
			os.Exit(1)
		}
		tunnelHTTPS()
	},
}

func init() {
	rootCmd.AddCommand(tlsCmd)
	tlsCmd.Flags().StringVarP(&Subdomain, "subdomain", "s", "", "If not selected domain name will be autogenerated")
	tlsCmd.Flags().BoolVarP(&GenerateCert, "generate-cert", "c", false, "Use this flag if you want us to automatically create a cert for you")

}
func tunnelHTTPS() {
	if Subdomain == "" || utilities.CheckSubdomain(Subdomain) {
		if utilities.CheckPort(Port) {
			//TODO: fix path to recognize ~/
			if GenerateCert {
				//Generate a cert
			} else {
				//use default key path
			}
			publicKey, err := utilities.GetPublicKey(PUBLIC_KEY_PATH)
			if err != nil {
				os.Exit(3)
			}

			response, err := restAPI.CreateTunnelAPI(Subdomain, publicKey, "https")
			if err != nil {
				fmt.Println(err.Error())
			} else {
				tunnelConfig := tunnel.TunnelConfig{
					RestApi:        restAPI,
					TunnelEndpoint: response,
					EndpointType:   "https",
					PrivateKeyPath: PRIVATE_KEY_PATH,
					EndpointUrl:    "holepunch.io",
					LocalPort:      Port,
					Subdomain:      Subdomain,
				}
				tunnel.StartReverseTunnel(&tunnelConfig)
				if err != nil {
					fmt.Println("Unable to setup reverse tunnel")
				} else {
				}
			}
		} else {
			fmt.Println("Port is not in range[1-65535")
		}
	} else {
		fmt.Println("Invalid Subdomain")
	}

}
